/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.erpcolegio.vista;


public class frmPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmPrincipal.class.getName());

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        configurarAccesos();
        configurarBarraEstado();
    }

    // metodo pora cambiar el contenido del panel
    public void mostrarPanel(javax.swing.JPanel panel){
        panel.setSize(pnlContenedor.getSize());
        panel.setLocation(0, 0);

        pnlContenedor.removeAll();
        pnlContenedor.add(panel, java.awt.BorderLayout.CENTER);
        pnlContenedor.revalidate();
        pnlContenedor.repaint();
    }
    
    // Método para habilitar/deshabilitar según el rol
    private void configurarAccesos() {
        com.erpcolegio.modelo.Usuario user = com.erpcolegio.util.SesionGlobal.usuarioActual;

        // Si por algún error llega nulo, lo devolvemos al login
        if (user == null) {
            this.dispose();
            new frmLogin().setVisible(true);
            return;
        }
        

        // Ocultar todos los menús por defecto por seguridad menos archivo
        menuMantenimiento.setVisible(false);
        menuAcademico.setVisible(false);
        menuMatriculas.setVisible(false);
        menuAsistencia.setVisible(false);
        menuEvaluaciones.setVisible(false);
        menuCierre.setVisible(false);

        

        // Mostramos según rol (1: Admin, 2: Director, 3: Secretaria, 4: Docente)
        String rol = user.getNombreRol();
    
        switch (rol) {
            case "ADMINISTRADOR":
                menuMantenimiento.setVisible(true);
                menuAcademico.setVisible(true);
                menuMatriculas.setVisible(true);
                menuAsistencia.setVisible(true);
                menuEvaluaciones.setVisible(true);
                menuCierre.setVisible(true);
                break;
            case "DIRECTOR":
                menuMantenimiento.setVisible(true);
                menuAcademico.setVisible(true);
                menuMatriculas.setVisible(true);
                menuAsistencia.setVisible(true);
                menuEvaluaciones.setVisible(true);
                menuCierre.setVisible(true);
                break;
            case "SECRETARIA":
                menuMantenimiento.setVisible(true);
                menuAcademico.setVisible(true);
                menuMatriculas.setVisible(true);
                break;
            case "DOCENTE":
                menuAsistencia.setVisible(true);
                menuEvaluaciones.setVisible(true);
                break;
        }

        this.setTitle("ERP Colegio SM - Usuario: " + user.getUsername());
    }
    
    private void configurarBarraEstado() {
        com.erpcolegio.modelo.Usuario user = com.erpcolegio.util.SesionGlobal.usuarioActual;

        if (user != null) {
            lblUsuario.setText("Usuario: " + user.getUsername());
            lblRol.setText("Rol: " + user.getNombreRol());

            com.erpcolegio.dao.AnioLectivoDAO anioDao = new com.erpcolegio.dao.AnioLectivoDAO();
            com.erpcolegio.modelo.AnioLectivo anio = anioDao.obtenerAnioVigente();

            if (anio != null) {
                lblAnio.setText("Año Lectivo Activo: " + anio.getAnio());
            } else {
                lblAnio.setText("Año Lectivo Activo: No configurado");
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContenedor = new javax.swing.JPanel();
        pnlBarraEstado = new javax.swing.JPanel();
        lblUsuario = new javax.swing.JLabel();
        lblRol = new javax.swing.JLabel();
        lblAnio = new javax.swing.JLabel();
        BarraMenu = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        menuMantenimiento = new javax.swing.JMenu();
        menuAcademico = new javax.swing.JMenu();
        menuMatriculas = new javax.swing.JMenu();
        menuAsistencia = new javax.swing.JMenu();
        menuEvaluaciones = new javax.swing.JMenu();
        menuCierre = new javax.swing.JMenu();
        menuAyuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlContenedor.setLayout(new java.awt.BorderLayout());

        lblUsuario.setText("jLabel1");

        lblRol.setText("jLabel1");

        lblAnio.setText("jLabel1");

        javax.swing.GroupLayout pnlBarraEstadoLayout = new javax.swing.GroupLayout(pnlBarraEstado);
        pnlBarraEstado.setLayout(pnlBarraEstadoLayout);
        pnlBarraEstadoLayout.setHorizontalGroup(
            pnlBarraEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBarraEstadoLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(lblRol, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 351, Short.MAX_VALUE)
                .addComponent(lblAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlBarraEstadoLayout.setVerticalGroup(
            pnlBarraEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBarraEstadoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlBarraEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAnio)
                    .addComponent(lblRol)
                    .addComponent(lblUsuario))
                .addContainerGap())
        );

        pnlContenedor.add(pnlBarraEstado, java.awt.BorderLayout.PAGE_END);

        menuArchivo.setText("Archivo");
        BarraMenu.add(menuArchivo);

        menuMantenimiento.setText("Mantenimiento");
        BarraMenu.add(menuMantenimiento);

        menuAcademico.setText("Académico");
        BarraMenu.add(menuAcademico);

        menuMatriculas.setText("Matrículas");
        BarraMenu.add(menuMatriculas);

        menuAsistencia.setText("Asistencias");
        BarraMenu.add(menuAsistencia);

        menuEvaluaciones.setText("Evaluaciones");
        BarraMenu.add(menuEvaluaciones);

        menuCierre.setText("Cierre y Actas");
        BarraMenu.add(menuCierre);

        menuAyuda.setText("Ayuda");
        BarraMenu.add(menuAyuda);

        setJMenuBar(BarraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar BarraMenu;
    private javax.swing.JLabel lblAnio;
    private javax.swing.JLabel lblRol;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JMenu menuAcademico;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenu menuAsistencia;
    private javax.swing.JMenu menuAyuda;
    private javax.swing.JMenu menuCierre;
    private javax.swing.JMenu menuEvaluaciones;
    private javax.swing.JMenu menuMantenimiento;
    private javax.swing.JMenu menuMatriculas;
    private javax.swing.JPanel pnlBarraEstado;
    private javax.swing.JPanel pnlContenedor;
    // End of variables declaration//GEN-END:variables
}
