/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.erpcolegio.vista;


public class pnlConfigAcademica extends javax.swing.JPanel {

    // variable de la clase controlador de configuracoin academica
    private com.erpcolegio.controlador.ConfigAcademicaController controlador;
    
    public pnlConfigAcademica() {
        initComponents();
        controlador = new com.erpcolegio.controlador.ConfigAcademicaController();
        cargarCombosEstaticos();
        cargarDatosBase();
        cargarTabla();
    }
    
    private void cargarCombosEstaticos() {
        cbNivel.removeAllItems();
        cbNivel.addItem("primaria");
        cbNivel.addItem("secundaria");

        cbTurno.removeAllItems();
        cbTurno.addItem("MAÑANA");
        cbTurno.addItem("TARDE");
    }  
    
    private void cargarDatosBase() {
        cbAnio.removeAllItems();
        for (com.erpcolegio.modelo.AnioLectivo anio : controlador.obtenerAnios()) {
            cbAnio.addItem(anio.getAnio()); 
        }

        cbSeccion.removeAllItems();
        for (com.erpcolegio.modelo.Seccion sec : controlador.obtenerSecciones()) {
            cbSeccion.addItem(sec.getNombreSeccion());
        }
    }
    
    private void cargarTabla() {
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tblAulas.getModel();
        modelo.setRowCount(0);

        for (com.erpcolegio.modelo.GradoSeccionAnio gsa : controlador.obtenerAulasConfiguradas()) {
            modelo.addRow(new Object[]{
                gsa.getAnioLectivoStr(),
                gsa.getNivelStr(),
                gsa.getGradoInt() + "° Grado",
                gsa.getSeccionStr(),
                gsa.getTurno(),
                gsa.getVacantes(),
                gsa.getVacantesOcupadas()
            });
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlConfAcademico = new javax.swing.JPanel();
        pnlAperturaAnio = new javax.swing.JPanel();
        lblAnio = new javax.swing.JLabel();
        txtAnio = new javax.swing.JTextField();
        lblFechaInicio = new javax.swing.JLabel();
        dcInicio = new com.toedter.calendar.JDateChooser();
        lblFechaFin = new javax.swing.JLabel();
        dcFin = new com.toedter.calendar.JDateChooser();
        btnAperturar = new javax.swing.JButton();
        pnlVacantes = new javax.swing.JPanel();
        lblAnioLectivo = new javax.swing.JLabel();
        cbAnio = new javax.swing.JComboBox<>();
        lblNivel = new javax.swing.JLabel();
        cbNivel = new javax.swing.JComboBox<>();
        lblGrado = new javax.swing.JLabel();
        cbGrado = new javax.swing.JComboBox<>();
        lblSecciones = new javax.swing.JLabel();
        cbSeccion = new javax.swing.JComboBox<>();
        lblTurno = new javax.swing.JLabel();
        cbTurno = new javax.swing.JComboBox<>();
        lblVacantes = new javax.swing.JLabel();
        txtVacantes = new javax.swing.JTextField();
        btnAgregarAula = new javax.swing.JButton();
        scrollTablaAulas = new javax.swing.JScrollPane();
        tblAulas = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        pnlAperturaAnio.setBorder(javax.swing.BorderFactory.createTitledBorder("Apertura del Año Lectivo"));

        lblAnio.setText("Año:");
        pnlAperturaAnio.add(lblAnio);
        pnlAperturaAnio.add(txtAnio);

        lblFechaInicio.setText("Inicio:");
        pnlAperturaAnio.add(lblFechaInicio);
        pnlAperturaAnio.add(dcInicio);

        lblFechaFin.setText("Fin:");
        pnlAperturaAnio.add(lblFechaFin);
        pnlAperturaAnio.add(dcFin);

        btnAperturar.setText("APERTURAR");
        btnAperturar.addActionListener(this::btnAperturarActionPerformed);
        pnlAperturaAnio.add(btnAperturar);

        pnlVacantes.setBorder(javax.swing.BorderFactory.createTitledBorder("Configuración de Vacantes por Grado/Sección"));
        pnlVacantes.setToolTipText("Solo para años vigentes");

        lblAnioLectivo.setText("Año Lectivo:");

        cbAnio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblNivel.setText("Nivel:");

        cbNivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbNivel.addItemListener(this::cbNivelItemStateChanged);

        lblGrado.setText("Grado:");

        cbGrado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblSecciones.setText("Sección a aperturar:");

        cbSeccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblTurno.setText("Turno:");

        cbTurno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblVacantes.setText("Vacantes:");

        txtVacantes.setText("jTextField2");

        btnAgregarAula.setText("AGREGAR AULA");
        btnAgregarAula.addActionListener(this::btnAgregarAulaActionPerformed);

        javax.swing.GroupLayout pnlVacantesLayout = new javax.swing.GroupLayout(pnlVacantes);
        pnlVacantes.setLayout(pnlVacantesLayout);
        pnlVacantesLayout.setHorizontalGroup(
            pnlVacantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVacantesLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(lblAnioLectivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cbAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(lblNivel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblGrado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbGrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110))
            .addGroup(pnlVacantesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSecciones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbSeccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(lblTurno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbTurno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(lblVacantes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtVacantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlVacantesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAgregarAula)
                .addGap(34, 34, 34))
        );
        pnlVacantesLayout.setVerticalGroup(
            pnlVacantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVacantesLayout.createSequentialGroup()
                .addGroup(pnlVacantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlVacantesLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(pnlVacantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAnioLectivo)
                            .addComponent(cbAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlVacantesLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(pnlVacantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNivel)
                            .addComponent(cbNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlVacantesLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(pnlVacantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGrado)
                            .addComponent(cbGrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(pnlVacantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlVacantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbTurno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblTurno)
                        .addComponent(lblVacantes)
                        .addComponent(txtVacantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlVacantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblSecciones)
                        .addComponent(cbSeccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btnAgregarAula)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblAulas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollTablaAulas.setViewportView(tblAulas);

        javax.swing.GroupLayout pnlConfAcademicoLayout = new javax.swing.GroupLayout(pnlConfAcademico);
        pnlConfAcademico.setLayout(pnlConfAcademicoLayout);
        pnlConfAcademicoLayout.setHorizontalGroup(
            pnlConfAcademicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConfAcademicoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnlConfAcademicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlAperturaAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlVacantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scrollTablaAulas, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlConfAcademicoLayout.setVerticalGroup(
            pnlConfAcademicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConfAcademicoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(pnlAperturaAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(pnlVacantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(scrollTablaAulas, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(pnlConfAcademico, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void cbNivelItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbNivelItemStateChanged
        // cambio dinamico de los grados
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            String nivelSel = cbNivel.getSelectedItem().toString();
            cbGrado.removeAllItems();
            for (com.erpcolegio.modelo.Grado g : controlador.obtenerGradosPorNivel(nivelSel)) {
                cbGrado.addItem(g.getGrado() + "° Grado");
            }
        }
    }//GEN-LAST:event_cbNivelItemStateChanged

    private void btnAgregarAulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarAulaActionPerformed
        int indexAnio = cbAnio.getSelectedIndex();
        int indexGrado = cbGrado.getSelectedIndex();
        int indexSeccion = cbSeccion.getSelectedIndex();

        if(indexAnio == -1 || indexGrado == -1 || indexSeccion == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Debe seleccionar Año, Grado y Sección.");
            return;
        }

        com.erpcolegio.modelo.AnioLectivo anioObj = controlador.obtenerAnios().get(indexAnio);
        String nivel = cbNivel.getSelectedItem().toString();
        com.erpcolegio.modelo.Grado gradoObj = controlador.obtenerGradosPorNivel(nivel).get(indexGrado);
        com.erpcolegio.modelo.Seccion seccionObj = controlador.obtenerSecciones().get(indexSeccion);

        String turno = cbTurno.getSelectedItem().toString();
        String vacantes = txtVacantes.getText().trim();

        if (controlador.agregarAula(anioObj, gradoObj, seccionObj, turno, vacantes)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Aula registrada correctamente.");
            cargarTabla();
            txtVacantes.setText("");
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Error de validación o el aula ya está configurada.");
        }
    }//GEN-LAST:event_btnAgregarAulaActionPerformed

    private void btnAperturarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAperturarActionPerformed
        String anio = txtAnio.getText().trim();
        java.util.Date inicio = dcInicio.getDate();
        java.util.Date fin = dcFin.getDate();

        if (controlador.aperturarAnio(anio, inicio, fin)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Año lectivo aperturado correctamente.");
            cargarDatosBase();
            txtAnio.setText("");
            dcInicio.setDate(null);
            dcFin.setDate(null);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: Verifique las fechas, el formato del año o si ya existe.");
        }
    }//GEN-LAST:event_btnAperturarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarAula;
    private javax.swing.JButton btnAperturar;
    private javax.swing.JComboBox<String> cbAnio;
    private javax.swing.JComboBox<String> cbGrado;
    private javax.swing.JComboBox<String> cbNivel;
    private javax.swing.JComboBox<String> cbSeccion;
    private javax.swing.JComboBox<String> cbTurno;
    private com.toedter.calendar.JDateChooser dcFin;
    private com.toedter.calendar.JDateChooser dcInicio;
    private javax.swing.JLabel lblAnio;
    private javax.swing.JLabel lblAnioLectivo;
    private javax.swing.JLabel lblFechaFin;
    private javax.swing.JLabel lblFechaInicio;
    private javax.swing.JLabel lblGrado;
    private javax.swing.JLabel lblNivel;
    private javax.swing.JLabel lblSecciones;
    private javax.swing.JLabel lblTurno;
    private javax.swing.JLabel lblVacantes;
    private javax.swing.JPanel pnlAperturaAnio;
    private javax.swing.JPanel pnlConfAcademico;
    private javax.swing.JPanel pnlVacantes;
    private javax.swing.JScrollPane scrollTablaAulas;
    private javax.swing.JTable tblAulas;
    private javax.swing.JTextField txtAnio;
    private javax.swing.JTextField txtVacantes;
    // End of variables declaration//GEN-END:variables
}
