/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.erpcolegio.vista;

public class pnlGestionColab extends javax.swing.JPanel {

    private com.erpcolegio.controlador.GestionColabController controlador;
    private java.util.List<com.erpcolegio.modelo.CategoriaColaborador> listaCargos;
    private java.util.List<com.erpcolegio.modelo.RegimenLaboral> listaRegimenes;
    private java.util.List<com.erpcolegio.modelo.Rol> listaRoles;
    
    public pnlGestionColab() {
        initComponents();
        controlador = new com.erpcolegio.controlador.GestionColabController();
        txtUsername.setEnabled(false); cbRol.setEnabled(false); txtPassword.setEnabled(false);
        cargarCatalogos();
        cargarCombosEstaticos();
    }
    
    private void cargarCatalogos() {
        listaCargos = controlador.obtenerCargos();
        cbCargo.removeAllItems();
        for(com.erpcolegio.modelo.CategoriaColaborador c : listaCargos) cbCargo.addItem(c.getPuestoColaborador());

        listaRegimenes = controlador.obtenerRegimenes();
        cbRegimen.removeAllItems();
        for(com.erpcolegio.modelo.RegimenLaboral r : listaRegimenes) cbRegimen.addItem(r.getNombreRegimen());

        listaRoles = controlador.obtenerRoles();
        cbRol.removeAllItems();
        for(com.erpcolegio.modelo.Rol r : listaRoles) cbRol.addItem(r.getNombreRol());
    }

    private void cargarCombosEstaticos() {
        cbCondicion.removeAllItems();
        cbCondicion.addItem("CONTRATADO");
        cbCondicion.addItem("NOMBRADO");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        pnlDatoPersonales = new javax.swing.JPanel();
        lblDNI = new javax.swing.JLabel();
        lblNombres = new javax.swing.JLabel();
        lblApellidos = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        txtDni = new javax.swing.JTextField();
        txtNombres = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        lblFechaNac = new javax.swing.JLabel();
        dcFechaNac = new com.toedter.calendar.JDateChooser();
        txtCorreo = new javax.swing.JTextField();
        btnBuscarDni = new javax.swing.JButton();
        pnlDatosLaborales = new javax.swing.JPanel();
        lblCargo = new javax.swing.JLabel();
        cbCargo = new javax.swing.JComboBox<>();
        lblRegimen = new javax.swing.JLabel();
        cbRegimen = new javax.swing.JComboBox<>();
        lblFechaInicio = new javax.swing.JLabel();
        dcInicioContrato = new com.toedter.calendar.JDateChooser();
        lblCondLaboral = new javax.swing.JLabel();
        cbCondicion = new javax.swing.JComboBox<>();
        pnlAccesoSistema = new javax.swing.JPanel();
        lblGenerar = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        chkGenerarUsuario = new javax.swing.JCheckBox();
        txtUsername = new javax.swing.JTextField();
        lblRol = new javax.swing.JLabel();
        cbRol = new javax.swing.JComboBox<>();
        lblClave = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        pnlBotones = new javax.swing.JPanel();
        btnNuevo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnCese = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        pnlDatoPersonales.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos personales"));

        lblDNI.setText("DNI:");

        lblNombres.setText("Nombes:");

        lblApellidos.setText("Apellidos:");

        lblTelefono.setText("Teléfono:");

        lblCorreo.setText("Correo:");

        lblFechaNac.setText("Fecha de Nacimiento:");

        btnBuscarDni.setText("Buscar");

        javax.swing.GroupLayout pnlDatoPersonalesLayout = new javax.swing.GroupLayout(pnlDatoPersonales);
        pnlDatoPersonales.setLayout(pnlDatoPersonalesLayout);
        pnlDatoPersonalesLayout.setHorizontalGroup(
            pnlDatoPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDatoPersonalesLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnlDatoPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlDatoPersonalesLayout.createSequentialGroup()
                        .addGroup(pnlDatoPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDatoPersonalesLayout.createSequentialGroup()
                                .addComponent(lblDNI)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnBuscarDni))
                            .addGroup(pnlDatoPersonalesLayout.createSequentialGroup()
                                .addComponent(lblFechaNac)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dcFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(109, 109, 109)
                                .addComponent(lblCorreo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlDatoPersonalesLayout.createSequentialGroup()
                        .addComponent(lblNombres)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                        .addComponent(lblApellidos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                        .addComponent(lblTelefono)
                        .addGap(18, 18, 18)
                        .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))))
        );
        pnlDatoPersonalesLayout.setVerticalGroup(
            pnlDatoPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatoPersonalesLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(pnlDatoPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDNI)
                    .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarDni))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDatoPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombres)
                    .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblApellidos)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelefono))
                .addGap(9, 9, 9)
                .addGroup(pnlDatoPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDatoPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCorreo)
                        .addComponent(lblFechaNac)
                        .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dcFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pnlDatosLaborales.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Laborales e Institucionales"));

        lblCargo.setText("Cargo:");

        cbCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblRegimen.setText("Régimen:");

        cbRegimen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblFechaInicio.setText("F. Inicio Contrato:");

        lblCondLaboral.setText("C. Laboral");

        cbCondicion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout pnlDatosLaboralesLayout = new javax.swing.GroupLayout(pnlDatosLaborales);
        pnlDatosLaborales.setLayout(pnlDatosLaboralesLayout);
        pnlDatosLaboralesLayout.setHorizontalGroup(
            pnlDatosLaboralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosLaboralesLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblCargo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(lblRegimen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbRegimen, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(lblFechaInicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dcInicioContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(lblCondLaboral)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbCondicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );
        pnlDatosLaboralesLayout.setVerticalGroup(
            pnlDatosLaboralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosLaboralesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDatosLaboralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dcInicioContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlDatosLaboralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCargo)
                        .addComponent(cbCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblRegimen)
                        .addComponent(cbRegimen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblFechaInicio))
                    .addGroup(pnlDatosLaboralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCondLaboral)
                        .addComponent(cbCondicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlAccesoSistema.setBorder(javax.swing.BorderFactory.createTitledBorder("Acceso al sistema"));
        pnlAccesoSistema.setToolTipText("");

        lblGenerar.setText("Generar Usuario:");
        lblGenerar.setToolTipText("Marque la casilla para empezar a crear un nuevo usuario");

        lblUsuario.setText("Usuario:");

        chkGenerarUsuario.addItemListener(this::chkGenerarUsuarioItemStateChanged);
        chkGenerarUsuario.addActionListener(this::chkGenerarUsuarioActionPerformed);

        txtUsername.setText("jTextField5");

        lblRol.setText("Rol:");

        cbRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblClave.setText("Clave:");

        javax.swing.GroupLayout pnlAccesoSistemaLayout = new javax.swing.GroupLayout(pnlAccesoSistema);
        pnlAccesoSistema.setLayout(pnlAccesoSistemaLayout);
        pnlAccesoSistemaLayout.setHorizontalGroup(
            pnlAccesoSistemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAccesoSistemaLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(pnlAccesoSistemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAccesoSistemaLayout.createSequentialGroup()
                        .addComponent(lblUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84)
                        .addComponent(lblRol)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbRol, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95)
                        .addComponent(lblClave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlAccesoSistemaLayout.createSequentialGroup()
                        .addComponent(lblGenerar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkGenerarUsuario)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlAccesoSistemaLayout.setVerticalGroup(
            pnlAccesoSistemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAccesoSistemaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAccesoSistemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGenerar)
                    .addComponent(chkGenerarUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlAccesoSistemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRol)
                    .addComponent(cbRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblClave)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlBotones.setToolTipText("");

        btnNuevo.setText("NUEVO");
        pnlBotones.add(btnNuevo);

        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);
        pnlBotones.add(btnGuardar);

        btnCese.setText("DAR CESE");
        btnCese.addActionListener(this::btnCeseActionPerformed);
        pnlBotones.add(btnCese);

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlDatoPersonales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(pnlAccesoSistema, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pnlDatosLaborales, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(pnlBotones, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(pnlDatoPersonales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlDatosLaborales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlAccesoSistema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(pnlBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        add(pnlPrincipal, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void chkGenerarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkGenerarUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkGenerarUsuarioActionPerformed

    private void chkGenerarUsuarioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkGenerarUsuarioItemStateChanged
        boolean activo = chkGenerarUsuario.isSelected();
        txtUsername.setEnabled(activo);
        cbRol.setEnabled(activo);
        txtPassword.setEnabled(activo);
    }//GEN-LAST:event_chkGenerarUsuarioItemStateChanged

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        boolean exito = controlador.guardarColaborador(
            txtDni.getText(), txtNombres.getText(), txtApellidos.getText(), dcFechaNac.getDate(),
            txtTelefono.getText(), txtCorreo.getText(), cbCargo.getSelectedIndex(), cbRegimen.getSelectedIndex(),
            cbCondicion.getSelectedItem().toString(), dcInicioContrato.getDate(),
            chkGenerarUsuario.isSelected(), txtUsername.getText(), new String(txtPassword.getPassword()), 
            cbRol.getSelectedIndex(), listaCargos, listaRegimenes, listaRoles
        );

        if(exito) {
            javax.swing.JOptionPane.showMessageDialog(this, "Colaborador registrado correctamente.");
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: Revise los datos, formato de DNI, o el usuario/DNI ya existe.");
        }
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCeseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCeseActionPerformed
        // se necesita un buscador del id del colaborador teniendo solo el dni
        
        int idColaboradorSeleccionado = 1; // REEMPLAZAR con el ID real cargado en el panel

        // Solicitamos contraseña del usuario en sesión
        javax.swing.JPasswordField pwd = new javax.swing.JPasswordField(10);
        int action = javax.swing.JOptionPane.showConfirmDialog(this, pwd, "Ingrese su contraseña para autorizar el Cese", javax.swing.JOptionPane.OK_CANCEL_OPTION);

        if (action == javax.swing.JOptionPane.OK_OPTION) {
            String inputPass = new String(pwd.getPassword());
            com.erpcolegio.controlador.LoginController login = new com.erpcolegio.controlador.LoginController();

            //  Re-validamos contra la bd usando el controller de Login
            if (login.procesarLogin(com.erpcolegio.util.SesionGlobal.usuarioActual.getUsername(), inputPass)) {

                com.erpcolegio.dao.ColaboradorDAO dao = new com.erpcolegio.dao.ColaboradorDAO();
                if(dao.cesarColaborador(idColaboradorSeleccionado)){
                    javax.swing.JOptionPane.showMessageDialog(this, "Cese lógico registrado. Contrato finalizado y usuario bloqueado.");
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this, "Error en la base de datos.");
                }
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Autorización denegada: Contraseña incorrecta.");
            }
        }
    }//GEN-LAST:event_btnCeseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarDni;
    private javax.swing.JButton btnCese;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox<String> cbCargo;
    private javax.swing.JComboBox<String> cbCondicion;
    private javax.swing.JComboBox<String> cbRegimen;
    private javax.swing.JComboBox<String> cbRol;
    private javax.swing.JCheckBox chkGenerarUsuario;
    private com.toedter.calendar.JDateChooser dcFechaNac;
    private com.toedter.calendar.JDateChooser dcInicioContrato;
    private javax.swing.JLabel lblApellidos;
    private javax.swing.JLabel lblCargo;
    private javax.swing.JLabel lblClave;
    private javax.swing.JLabel lblCondLaboral;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblDNI;
    private javax.swing.JLabel lblFechaInicio;
    private javax.swing.JLabel lblFechaNac;
    private javax.swing.JLabel lblGenerar;
    private javax.swing.JLabel lblNombres;
    private javax.swing.JLabel lblRegimen;
    private javax.swing.JLabel lblRol;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel pnlAccesoSistema;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JPanel pnlDatoPersonales;
    private javax.swing.JPanel pnlDatosLaborales;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
